apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sith-neural-net
  namespace: redsaber
spec:
  project: default
  source:
    repoURL: https://gitlab.com/<your-group>/hello-nginx.git
    targetRevision: main
    path: k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: redsaber
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
