apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sith-neural-net
  namespace: argocd
spec:
  project: default
  source:    
    repoURL: https://gitlab.com/holocron-lab/sith-ops.git
    targetRevision: main
    path: hello-nginx/helm
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: exegol
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true