stages:
  - build
  - deploy

variables:
  IMAGE: registry.gitlab.com/$CI_PROJECT_PATH/hello-nginx

build:
  stage: build
  image: gcr.io/kaniko-project/executor:debug
  variables:
    DOCKER_CONFIG: /kaniko/.docker
  script:
    - /kaniko/executor 
      --dockerfile Dockerfile
      --destination $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA
      --context $CI_PROJECT_DIR
  tags:
    - sith-ops

deploy:
  stage: deploy
  image: alpine:latest
  before_script:
    - apk add --no-cache git
  script:
    # Update image tag in values.yaml
    - 'sed -i "s|tag: .*|tag: $CI_COMMIT_SHORT_SHA|g" hello-nginx/helm/values.yaml'
    # Commit changes
    - 'git config user.email "mustafar.ops@gmail.com"'
    - 'git config user.name "ops-admin"'
    - git add hello-nginx/helm/values.yaml
    - 'git commit -m "ci: deploy $CI_COMMIT_SHORT_SHA"'
    - 'git push https://gitlab-ci-token:$CI_JOB_TOKEN@gitlab.com/$CI_PROJECT_PATH.git HEAD:main'
  only:
    - main
  tags:
    - sith-ops