stages:
  - build
  - deploy

variables:
  IMAGE: registry.gitlab.com/$CI_PROJECT_PATH/hello-nginx

build:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:latest
    entrypoint: [""]  # Override the default entrypoint
  variables:
    DOCKER_CONFIG: /kaniko/.docker
  script:
    - /kaniko/executor 
      --dockerfile Dockerfile
      --destination $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA
      --context $CI_PROJECT_DIR
  tags:
    - sith-ops

deploy:
  stage: deploy
  image: alpine:latest
  script:
    - 'sed -i "s|image: .*$|image: $IMAGE:$CI_COMMIT_SHORT_SHA|g" k8s/deployment.yaml"'
    - 'git config user.email "mustafar.ops@gmail.com"'
    - 'git config user.name  "ops-admin"'
    - git add k8s/deployment.yaml
    - 'git commit -m "ci: deploy $CI_COMMIT_SHORT_SHA"'
    - 'git push https://$CI_PROJECT_PATH:$CI_JOB_TOKEN@gitlab.com/$CI_PROJECT_PATH.git HEAD:main'
  only:
    - main
  tags:
    - sith-ops
