replicaCount: 2

image:
  repository: registry.gitlab.com/holocron-lab/holocron-red/sith-ops/hello-nginx
  tag: latest
  pullPolicy: Always

# Image pull secrets
imagePullSecrets:
  - name: gitlab-registry

service:
  type: ClusterIP
  port: 80
  targetPort: 80

# App labels and metadata
app:
  name: sith-neural-net

# Namespace
namespace: exegol

resources: {}
nodeSelector: {}
tolerations: []
affinity: {}