stages:
  - build
  - deploy

variables:
  IMAGE: registry.gitlab.com/$CI_PROJECT_PATH/hello-nginx

build:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker build -t $IMAGE:$CI_COMMIT_SHORT_SHA .
    - docker push $IMAGE:$CI_COMMIT_SHORT_SHA

deploy:
  stage: deploy
  image: alpine:latest
  script:
    # Update the k8s/deployment.yaml with the new image tag
    - sed -i "s|image: .*$|image: $IMAGE:$CI_COMMIT_SHORT_SHA|g" k8s/deployment.yaml
    # Commit & push the updated manifest back to the repo
    - git config user.email "ci@example.com"
    - git config user.name  "GitLab CI"
    - git add k8s/deployment.yaml
    - git commit -m "ci: deploy $CI_COMMIT_SHORT_SHA"
    - git push https://$CI_PROJECT_PATH:$CI_JOB_TOKEN@gitlab.com/$CI_PROJECT_PATH.git HEAD:main
  only:
    - main
